"""Add thumbnails

Revision ID: 596ea4e85025
Revises: 9bdecc70abf5
Create Date: 2024-10-21 20:26:10.588376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596ea4e85025'
down_revision = '9bdecc70abf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
