"""more cascades

Revision ID: 84a25d5d5551
Revises: f6a92057073f
Create Date: 2024-12-11 22:44:26.945489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a25d5d5551'
down_revision = 'f6a92057073f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('fk_image_comparison_id_comparison', type_='foreignkey')
        batch_op.drop_constraint('constr_image_dataset', type_='foreignkey')
        batch_op.drop_constraint('fk_image_result_id_result', type_='foreignkey')
        batch_op.create_foreign_key('fk_image_comparison_id_comparison', 'comparison', ['comparison_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('constr_image_dataset', 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_image_result_id_result', 'result', ['result_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('image_element', schema=None) as batch_op:
        batch_op.drop_constraint('fk_image_element_image_id_image', type_='foreignkey')
        batch_op.create_foreign_key('fk_image_element_image_id_image', 'image', ['image_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_element', schema=None) as batch_op:
        batch_op.drop_constraint('fk_image_element_image_id_image', type_='foreignkey')
        batch_op.create_foreign_key('fk_image_element_image_id_image', 'image', ['image_id'], ['id'])

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('fk_image_result_id_result', type_='foreignkey')
        batch_op.drop_constraint('constr_image_dataset', type_='foreignkey')
        batch_op.drop_constraint('fk_image_comparison_id_comparison', type_='foreignkey')
        batch_op.create_foreign_key('fk_image_result_id_result', 'result', ['result_id'], ['id'])
        batch_op.create_foreign_key('constr_image_dataset', 'dataset', ['dataset_id'], ['id'])
        batch_op.create_foreign_key('fk_image_comparison_id_comparison', 'comparison', ['comparison_id'], ['id'])

    # ### end Alembic commands ###
