"""add classification leaders

Revision ID: f414dd2fc318
Revises: 4437da380ec5
Create Date: 2024-10-29 22:15:05.474246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f414dd2fc318'
down_revision = '4437da380ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_leader', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_element', schema=None) as batch_op:
        batch_op.drop_column('is_leader')

    # ### end Alembic commands ###
